name: Deploy to Vercel

on:
  push:
    branches:
      - website  # This will trigger on pushes to the website branch
      - main     # Also trigger on pushes to main branch
  pull_request:
    types:
      - closed   # Trigger when PRs are merged

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_DQgT4Uj2p4OE60K5NeuwzC8G3bBx/lWWVsvEqjO"
      
      - name: Verify deployment
        run: |
          echo "Deployment triggered. Check your Vercel dashboard for deployment status."
          echo "Visit your site at https://solarbot.vercel.app (or your custom domain) to verify the deployment."
